# Generated by Django 4.2.14 on 2024-08-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='cost')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('mileage', models.IntegerField(default=0)),
                ('with_photo', models.BooleanField(blank=True, default=True, null=True)),
                ('drive', models.CharField(choices=[('задный', 'задный'), ('передний', 'передний'), ('полны', 'полны')], max_length=16, verbose_name='Привод')),
                ('engine', models.CharField(choices=[('бензин', 'бензин'), ('газ', 'газ'), ('дизель', 'дизель'), ('электрический', 'электрический')], max_length=16)),
                ('volume', models.FloatField(default=0.8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carmake')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carmodel')),
            ],
        ),
    ]
